openapi: 3.0.0
info:
  title: rAPP Catalogue API
  description: The Non RT-RIC Service Catalogue provides a way for services to register
    themselves for other services to discover.
  version: 1.0.0
servers:
- url: /
paths:
  /services:
    get:
      tags:
      - rAPP Catalogue API
      summary: Service names
      operationId: getServiceNamesUsingGET
      responses:
        200:
          description: Service names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example:
              - DroneIdentifier
              - Collector
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not used
      deprecated: false
  /services/{serviceName}:
    get:
      tags:
      - rAPP Catalogue API
      summary: Individual Service
      operationId: getIndividualServiceUsingGET
      parameters:
      - name: serviceName
        in: path
        description: serviceName
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: DroneIdentifier
      responses:
        200:
          description: EI Job
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Service is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_information'
      deprecated: false
    put:
      tags:
      - rAPP Catalogue API
      summary: Create or update a Service
      operationId: putIndividualServiceUsingPUT
      parameters:
      - name: serviceName
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: DroneIdentifier
      requestBody:
        description: Service to create/update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/service'
        required: true
      responses:
        200:
          description: Service updated
        201:
          description: Service created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Provided service is not correct
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_information'
              example:
                detail: Service is missing required property version
                status: 404
      deprecated: false
    delete:
      tags:
      - rAPP Catalogue API
      summary: Remove a Service from the catalogue
      operationId: deleteIndividualServiceUsingDELETE
      parameters:
      - name: serviceName
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: DroneIdentifier
      responses:
        200:
          description: Not used
        204:
          description: Job deleted
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Service is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_information'
      deprecated: false
components:
  schemas:
    service:
      title: service
      required:
      - version
      type: object
      properties:
        version:
          type: string
          description: Version of the Service
          example: 1.0.0
        display_name:
          type: string
          description: Display name for the Service
          example: Drone Identifier
        description:
          type: string
          description: Description of the Service
          example: Detects if a UE is a drone
      description: A Service
    error_information:
      title: error_information
      type: object
      properties:
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of
            the problem.
          example: Service not found
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this
            occurrence of the problem.
          format: int32
          example: 404
      description: Problem as defined in https://tools.ietf.org/html/rfc7807
